/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoumPuted: typeof import('./src/components/coumPuted.vue')['default']
    ElB: typeof import('element-plus/es')['ElB']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ExDemo: typeof import('./src/components/exDemo.vue')['default']
    NewTest: typeof import('./src/components/newTest.vue')['default']
    PersionDemo: typeof import('./src/components/PersionDemo.vue')['default']
    UserInfo: typeof import('./src/components/userInfo.vue')['default']
    WatchDemo: typeof import('./src/components/watchDemo.vue')['default']
    WatchEffwct: typeof import('./src/components/watchEffwct.vue')['default']
  }
}
