/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ExDemo: typeof import('./src/components/exDemo.vue')['default']
    NewTest: typeof import('./src/components/newTest.vue')['default']
    PersionDemo: typeof import('./src/components/PersionDemo.vue')['default']
  }
}
